server:
    contextPath: /${spring.application.name}
    port: 8000
spring:
  profiles:
    include: subversion
  cloud:
    config:
      server:
        svn:
          username: <user name>
          password: <pwd>
          uri: <uri>
          searchPaths: '/{profile}/' 
          basedir: temp//config
        default-label: ''   
logging:
   file: ${LOG4J_DIR}/config-server.log